### ISSUE TITLE
Issue with the ai inputs - text under transparent buttons

### ISSUE THREAD

**Issue by real-marty** [kokonut-labs/kokonutui#1]
Hello, by the way I realy appriciate your library, looks awesome.

Might be a quickie four you.

When i add a lot of text to the AI imput field it goes under the buttons in some cases.

**
![image](https://github.com/user-attachments/assets/468021a8-0cdd-4366-8f13-b980ec836fb0)
**

**Comment by dorianbaffier-dev** [comment]
Thank you! 

Fixed in commit efe464b
